#version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Microchip.Interview.Api/Dockerfile
    image: publications-api:latest
    container_name: publications_api
    environment:
      ASPNETCORE_URLS: http://+:8080
    expose:      
      - "8080"      # internal network only    
    # no host ports; proxy reaches it by service name
    #ports:
    #  - "5031:8080"  # host:container
  

  client:
    build:
      context: ./client/publications-client
      dockerfile: Dockerfile
    image: publications-client:latest
    container_name: publications_client
    expose:
      - "80"   # internal network only
    #ports:
    #  - "5173:80"    # host:container
    depends_on:
      - api

  reverse-proxy:    
    image: nginx:alpine
    container_name: publications_reverse_proxy
    volumes:
      - ./reverse-proxy/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"         # single public port
    depends_on:      
      - api      
      - client
