version: "3.9"

services:

  api:
    container_name: publications_api
    build:
      context: .
      dockerfile: Microchip.Interview.Api/Dockerfile
    image: publications-api:latest
    expose:
      - "8080"
    environment:
      ASPNETCORE_URLS: http://+:8080
    restart: always
    networks:
      - appnet

  client:
    container_name: publications_client
    build:
      context: ./client/publications-client
      dockerfile: Dockerfile
    image: publications-client:latest
    expose:
      - "80"
    depends_on:
      - api
    restart: always
    networks:
      - appnet

  reverse-proxy:
    container_name: publications_reverse_proxy
    image: nginx:alpine
    volumes:
      - ./reverse-proxy/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - api
      - client
    restart: always
    networks:
      - appnet

networks:
  appnet:
    driver: bridge